#pragma once

enum {
	PS_CARRY,
	PS_ZERO,
	PS_INTERRUPT_DISABLE,
	PS_DECIMAL_MODE,
	PS_BREAK,
	PS_OVERFLOW,
	PS_NEGATIVE,
};

enum machine_register {
	REG_A,
	REG_PS,
	REG_S,
	REG_X,
	REG_Y,
	TOTAL_CPU_REGS,
};

enum instruction {
	INS_INVALID,

	// JMA -> JMP ABSOLUTE
	INS_ORA, INS_AND, INS_EOR, INS_ADC,
	INS_STA, INS_LDA, INS_CMP, INS_SBC,
	INS_ASL, INS_ROL, INS_LSR, INS_ROR,
	INS_STX, INS_LDX, INS_DEC, INS_INC,
	INS_BIT, INS_JMP, INS_JMA, INS_STY,
	INS_LDY, INS_CPY, INS_CPX,

	INS_BPL, INS_BMI, INS_BVC, INS_BVS,
	INS_BCC, INS_BCS, INS_BNE, INS_BEQ,
	INS_BRK, INS_JSR, INS_RTI, INS_RTS,

	INS_PHP, INS_PLP, INS_PHA, INS_PLA,
	INS_DEY, INS_TAY, INS_INY, INS_INX,
	INS_CLC, INS_SEC, INS_CLI, INS_SEI,
	INS_TYA, INS_CLV, INS_CLD, INS_SED,
	INS_TXA, INS_TXS, INS_TAX, INS_TSX,
	INS_DEX, INS_NOP,
};

enum addressing_mode {
	ADDR_MODE_INVALID,
	ADDR_MODE_NONE,
	ADDR_MODE_IMM,
	ADDR_MODE_ACC,
	ADDR_MODE_REL,
	ADDR_MODE_ZERO,
	ADDR_MODE_ZERO_X,
	ADDR_MODE_ZERO_Y,
	ADDR_MODE_ABS,
	ADDR_MODE_ABS_X,
	ADDR_MODE_ABS_Y,
	ADDR_MODE_IND,
	ADDR_MODE_IND_X,
	ADDR_MODE_IND_Y,
};

struct opcode {
	enum instruction ins;
	enum addressing_mode addr_mode;
};

#define INSTRUCTION_GROUPS	3
#define INSTRUCTION_GROUP_MAX	8

static enum instruction instruction_table[INSTRUCTION_GROUPS][INSTRUCTION_GROUP_MAX] = {
	{ INS_BIT, INS_JMP, INS_JMA, INS_STY, INS_LDY, INS_CPY, INS_CPX, INS_INVALID },
	{ INS_ORA, INS_AND, INS_EOR, INS_ADC, INS_STA, INS_LDA, INS_CMP, INS_SBC },
	{ INS_ASL, INS_ROL, INS_LSR, INS_ROR, INS_STX, INS_LDX, INS_DEC, INS_INC },
};

static enum instruction special_instruction_table[256] = {
	[0x00] = INS_BRK, [0x20] = INS_JSR, [0x40] = INS_RTI, [0x60] = INS_RTS,
	[0x10] = INS_BPL, [0x30] = INS_BMI, [0x50] = INS_BVC, [0x70] = INS_BVS,
	[0x90] = INS_BCC, [0xB0] = INS_BCS, [0xD0] = INS_BNE, [0xF0] = INS_BEQ,
	[0x08] = INS_PHP, [0x28] = INS_PLP,  [0x48] = INS_PHA, [0x68] = INS_PLA,
	[0x88] = INS_DEY, [0xA8] = INS_TAY, [0xC8] = INS_INY, [0xE8] = INS_INX,
	[0x18] = INS_CLC, [0x38] = INS_SEC, [0x58] = INS_CLI, [0x78] = INS_SEI,
	[0x98] = INS_TYA, [0xB8] = INS_CLV, [0xD8] = INS_CLD, [0xF8] = INS_SED,
	[0x8A] = INS_TXA, [0x9A] = INS_TXS, [0xAA] = INS_TAX, [0xBA] = INS_TSX,
	[0xCA] = INS_DEX, [0xEA] = INS_NOP,
};

static enum addressing_mode addressing_mode_table[INSTRUCTION_GROUPS][INSTRUCTION_GROUP_MAX] = {
	{
		ADDR_MODE_IMM,
		ADDR_MODE_ZERO,
		ADDR_MODE_INVALID,
		ADDR_MODE_ABS,
		ADDR_MODE_INVALID,
		ADDR_MODE_ZERO_X,
		ADDR_MODE_INVALID,
		ADDR_MODE_ABS_X,
	},
	{
		ADDR_MODE_ZERO_X,
		ADDR_MODE_ZERO,
		ADDR_MODE_IMM,
		ADDR_MODE_ABS,
		ADDR_MODE_IND_Y,
		ADDR_MODE_IND_X,
		ADDR_MODE_ABS_Y,
		ADDR_MODE_ABS_X,
	},
	{
		ADDR_MODE_IMM,
		ADDR_MODE_ZERO,
		ADDR_MODE_ACC,
		ADDR_MODE_ABS,
		ADDR_MODE_INVALID,
		ADDR_MODE_ZERO_X,
		ADDR_MODE_INVALID,
		ADDR_MODE_ABS_X,
	}
};

#define OPCODE_AAA(o)	((o) >> 5)
#define OPCODE_BBB(o)	(((o) >> 2) & 7)
#define OPCODE_CC(o)	((o) & 3)

#define KB(n)	((n) * (2 << 10))

#define ZERO_PAGE_LEN		256
#define STACK_PAGE_LEN		256
#define MEMORY_AVAILABLE	KB(64)

#define INT_HANDLER		0xFFFA
#define POW_HANDLER		0XFFFC
#define IRQ_HANDLER		0xFFFE

#define CPU_CLOCK_RATE_US	3
